flux-framework/dyad

- configure.ac
Have `autoconfig` find DYAD version from git tag.
> Build: automatically track the version based on git tag

- run/flux/gen.sh
In the script that generates job scripts for experimenting producer-consumer patterns, a barrier is used before starting any of producer and consumer such that they all can start at the same time regardless of the scheduler delay. This is to help obtain better measurements.
> exp: add the barrier in the producer-consumer experiment script generation

- src/wrapper/wrapper.c
DYAD currently detects the synchronization need by environment variable.
Users need to set appropriate variable to tell DYAD I/O interceptor which file access to synchronize. However, this has a limitation as a process can open multiple files with different modes. A consumer can be a producer at the same time, and vice versa. This PR removes the need for environment variable. For a file about to be closed, it utilizes the system call `fcntl()` to detect if a file has been open in the write mode. For a file about to be opened, the mode argument can be checked easily. This addresses issue #10
> Wrapper: automatically detect if the file access sync need

- docs/demos/ecp_feb_2023/cons.cpp
- docs/demos/ecp_feb_2023/prod.cpp
There was a small mistake in the C++ demo code that would cause `memcpy` to not be found with some implementations of the C++ Standard Library. This PR fixes that by adding `#include <cstring>`
> Fixes the includes in the C++ demo code

- docs/getting_started.rst
- dyadrun.in
- run/flux/gen.sh
- run/flux/separate_steps.template.sh
- run/merlin/separate_steps.yaml
- run/merlin/single_step.yaml
- run/merlin/templates/gen.sh
- run/merlin/templates/separate_steps.template.yaml
- run/user_apps/args.sh
- src/stream/test/args.sh
- src/wrapper/Makefile.am
- src/wrapper/README.md
- src/wrapper/test/args.sh
Changing `libdyad_sync.so` to `dyad_wrapper.so`
This is basedon PR #22. Once it is merged, I will rebase this. That will leave only the change relevant to this visible.
TODO: Make sure the ECP tutorial uses the version it was created with using git tag
> Wrapper name change

- src/core/Makefile.am
- src/core/dyad_core.sym
- src/modules/Makefile.am
- src/wrapper/Makefile.am
- src/wrapper/wrapper.c
- src/wrapper/wrapper.sym
DYAD's various libraries were previously exporting a lot of symbols that were not supposed to be exported. This PR fixes this using libtool's `-export-symbols` and `-export-symbols-regex` flags.
> Hotfix: updates build system to prevent excessive symbol exports

- src/core/dyad_core.sym
- src/wrapper/wrapper.sym
During the review of #26, we noticed that GitHub didn't like the lack of a newline at the end of our `.sym` files, so we added those newlines. However, the addition of those newlines breaks Autotools builds. This PR adds those newlines back to the `.sym` files to fix DYAD's build process
> Hotfix: removes blank lines from end of .sym files because they break builds

- .github/workflows/compile_test.yaml
Closes #35 
The GitHub Action for testing the compilation works was merged a bit too early. This PR fixes the issues that were cropping up with the action.
> Gets the compile test action working

- configure.ac
- src/core/Makefile.am
- src/dtl/Makefile.am
- src/modules/Makefile.am
This PR reworks `configure.ac` and all the relevant `Makefile.am`s to make UCX an optional dependency for DYAD.
> Makes UCX an optional dependency

- .github/prod-cons/dyad_consumer.sh
- .github/prod-cons/dyad_prod_cons_test.sh
- .github/prod-cons/dyad_producer.sh
- .github/prod-cons/prod_cons_argparse.sh
- .github/workflows/compile_test.yaml
- .gitignore
- pydyad/pydyad/__init__.py
- pydyad/pydyad/bindings.py
- pydyad/pydyad/context.py
- pydyad/pyproject.toml
- pydyad/setup.cfg
- pydyad/setup.py
- tests/pydyad_spsc/README.md
- tests/pydyad_spsc/consumer.py
- tests/pydyad_spsc/producer.py
- tests/pydyad_spsc/run.sh
This PR adds a dedicated Python API to DYAD. This API will not be built/installed by Autotools. Instead, it will use setuptools/pip for its build/install process. This will allow us to host the Python API on PyPI if desired.
In terms of the interface, there are only 3 things a user may have to interact with:
1. The `dyad_open` function
2. The `dyad_open_local` function
3. The `Dyad` class
Most users will only use `dyad_open`. This function is a drop-in replacement for the built-in `open` function. Internally, this function is a "context manager" (see [this page](https://docs.python.org/3/library/contextlib.html) for more info). It creates a global `Dyad` object (if not created previously) and uses the `Dyad` object and built-in `open` function to carry out data production/consumption. …
> Adds a dedicated Python API

- configure.ac
- src/dtl/Makefile.am
- src/dtl/dyad_dtl_impl.c
- src/stream/Makefile.am
- src/wrapper/Makefile.am
#49 made UCX an optional dependency. However, it did not make the UCX-based code in `dyad_dtl_init` and `dyad_dtl_finalize` conditionally compiled. As a result, if a user built DYAD without `--enable-ucx` and then set the DTL mode to `UCX`, failures would occur due to `dyad_dtl_init` and `dyad_dtl_finalize` trying to call the corresponding UCX DTL functions, which would not have been built.
This hotfix PR fixes this small, but important, bug.
> Hotfix: various build system fixes to support CI

- .clang-format
- pydyad/pydyad/bindings.py
- src/core/dyad_core.c
- src/core/dyad_core.h
- src/dtl/dyad_rc.h
This PR adds a new function to the Core library: `dyad_get_metadata`. This function accepts a file path as input, and, if metadata about that file is found in the Flux KVS, it will return that metadata to the user.
Additionally, this PR adds Python bindings to the new `dyad_get_metadata` function.
Due to the Python binding, this PR depends on #27
> Adds a function to get DYAD file metadata

- .github/workflows/compile_test.yaml
- tests/pydyad_spsc/README.md
- tests/pydyad_spsc/consumer.py
- tests/pydyad_spsc/run.sh
tests/pydyad_spsc seems to have multiple issues.
- `KVS_NAMESPACE` variable is inconsistently used with `DYAD_KVS_NAMESPACE`
- DYAD managed directory is not created.
- In case that such a directory already exists, and the directory contains the files from the previous runs, the test is invalid
- module load uses producer's managed path which is misleading due to the variable name
- Depending on the DTL mode, it shows different errors
> Test: fix some issues with python API test

- pydyad/pydyad/bindings.py
- pydyad/pydyad/context.py
- src/dyad/common/dyad_structures.h
- src/dyad/core/dyad_core.c
- src/dyad/core/dyad_core.h
- src/dyad/dtl/dyad_dtl_api.c
- src/dyad/dtl/dyad_dtl_api.h
- src/dyad/dtl/flux_dtl.c
- src/dyad/dtl/ucx_dtl.c
- src/dyad/dtl/ucx_dtl.h
- src/dyad/dtl/ucx_ep_cache.cpp
- src/dyad/dtl/ucx_ep_cache.h
- src/dyad/modules/dyad.c
- tests/integration/dlio_benchmark/configs/workload/dyad_unet3d.yaml
- tests/integration/dlio_benchmark/dyad_torch_data_loader.py
1. Fixes a bug in `dyad_consume()` that returns the buffer that has never been assigned.
2. Adds an variant interface of `dyad_consume()` that relies on the metadata that has already been pulled from KVS 
3. Still need to add a python interface: note that the new interface `dyad_consume_w_mdata(..., mdata)` deallocates mdata internally. We can change this behavior depending on how we want to write python interface.
> Consume after kvs pull

- .github/workflows/compile_test.yaml
DLIO test requires Python API.
So, it makes sense to move it after Python API test.
We will also be able to see the test result with c core first.
> Move the DLIO test after Python API test

- src/dyad/core/dyad_core.c
- src/dyad/utils/CMakeLists.txt
- src/dyad/utils/test_murmur3.c
- src/dyad/utils/utils.c
Strings shorter than 128 bytes collide possible due to the implementation details of `MurmurHash3_x64_128()`. Especially, the hash value seems to depend on the length of such a string.
For such a short string, we concatenate it as many times as needed to make it longer than 128 bytes.
Added a test to show hash results.
For example, before this fix,  `test_murmur3 3 1024 data1.txt data2.txt data3.txt 123456.txt 1data5.txt data91.txt` showed the following results
```
data1.txt	199.ca.3e.data1.txt
data2.txt	199.ca.3e.data2.txt
data3.txt	199.ca.3e.data3.txt
123456.txt	37e.c8.89.123456.txt
1data5.txt	37e.c8.89.1data5.txt
data91.txt	37e.c8.89.data91.txt
```
After the fix, the below is the new results.
```
data1.txt	2cd.1cd.3cc.data1.txt
data2.txt	11f.2cb.5a.data2.txt
data3.txt …
```
> improve hash distribution with short strings

- docs/demos/ecp_feb_2023/Makefile
- src/dyad/core/dyad_core.c
- src/dyad/dtl/flux_dtl.c
- src/dyad/dtl/ucx_dtl.c
- src/dyad/modules/dyad.c
- src/dyad/stream/dyad_stream_core.cpp
Fix the recv function of flux rpc based dtl.
This is to change the flux_future_destroy back to flux_future_reset for streaming RPC.
This is a bug I introduced some time ago.
> change future destroy back to future reset in flux dtl recv

- .readthedocs.yaml
- docs/requirements.txt
This PRs adds the fixes we discussed yesterday to enable CI-driven doc builds on PRs. It creates a `.readthedocs.yaml` file and pins the version of Sphinx to prevent issues with newer versions of ReadTheDocs.
> Fixes to get ReadTheDocs builds on PRs working

- src/dyad/modules/dyad.c
1. Removed unused variables.
2. Changed several outputs from STDERR to STDOUT.
3. Deleted a few debug output messages.
> Cleaning the FLUX module code

- .github/prod-cons/dyad_consumer.sh
- .github/prod-cons/dyad_producer.sh
- .github/prod-cons/prod_cons_argparse.sh
- docs/demos/ecp_feb_2023/Makefile
Currently, dyad library path is hard-coded as 'lib' in test scripts.
Allow 'lib64' as the dyad library installation path.
> Allow lib64 as the dyad library installation path in test scripts

- src/dyad/client/dyad_client.c
- src/dyad/common/dyad_structures_int.h
- src/dyad/dtl/ucx_dtl.c
- src/dyad/dtl/ucx_ep_cache.cpp
- src/dyad/modules/dyad.c
- src/dyad/utils/utils.c
Hyojin's app uses large files which needs to use granularity to make sure POSIX does not fail.
Also reducing some prints which are excessive.
> Fixes for large file
